import { randomUUID } from "crypto";
export const pets = [
  {
    id: randomUUID(),
    name: "Spike",
    breed: "SRD",
    age: 15,
    ownerName: "Roger",
    registration: true,
  },
  {
    id: randomUUID(),
    name: "Bob",
    breed: "Pinscher",
    age: 8,
    ownerName: "Carina",
    registration: true,
  },
  {
    id: randomUUID(),
    name: "Clei",
    breed: "Pitbull",
    age: 10,
    ownerName: "Noe",
    registration: true,
  },
  {
    id: randomUUID(),
    name: "Mel",
    breed: "Pug",
    age: 3,
    ownerName: "Clara",
    registration: true,
  },
  {
    id: randomUUID(),
    name: "Thor",
    breed: "Golden Retriever",
    age: 8,
    ownerName: "Regis",
    registration: true,
  },
  {
    id: randomUUID(),
    name: "Shiva",
    breed: "Chihuahua",
    age: 15,
    ownerName: "Eliana",
    registration: true,
  },
];
